workflows:
  flutter-workflow:
    name: Flutter Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: |
          cd flutter_app
          flutter pub get
      - name: Build APK
        script: |
          cd flutter_app
          flutter build apk
