workflows:
  flutter_build:
    name: Flutter Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: |
          cd $CM_BUILD_DIR/flutter_AppCoffe
          flutter pub get
      - name: Build APK
        script: |
          cd $CM_BUILD_DIR/flutter_AppCoffe
          flutter build apk --release
    artifacts:
      - flutter_AppCoffe/build/app/outputs/flutter-apk/*.apk
