workflows:
  flutter_build:
    name: Flutter Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    scripts:
      - name: Check Java Version
        script: |
          echo "Using JAVA_HOME: $JAVA_HOME"
          java -version
      - name: Get Flutter dependencies
        script: |
          cd $CM_BUILD_DIR/flutter_AppCoffe
          flutter pub get
      - name: Build APK
        script: |
          cd $CM_BUILD_DIR/flutter_AppCoffe
          flutter build apk --release --stacktrace
    artifacts:
      - flutter_AppCoffe/build/app/outputs/flutter-apk/*.apk
